project:
  type: website
  output-dir: docs

website:
  title: "Rat Genomics Pipeline Rendered"
  navbar:
    left:
      - href: index.qmd
        text: paper_code
      - href: other_code.qmd
        text: more_code

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

listing:
  contents: posts
  sort: "title"
  
execute:
  eval: false